/* ============================================================================
 * store.js — File-based project store (no external database).
 *
 * Each project is a single JSON document on disk:
 *   { id, name, rev, createdAt, updatedAt, model }
 * The shared library is simply the contents of the data directory, so any
 * number of users hitting the same server see the same projects. Saves use an
 * optimistic-concurrency `rev` counter so a stale client can't silently clobber
 * someone else's write.
 * ==========================================================================*/
"use strict";
const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");

class Store {
  constructor(dir) {
    this.dir = dir;
  }

  async init() {
    await fs.mkdir(this.dir, { recursive: true });
  }

  _file(id) {
    // ids are generated by us (hex), but guard against path traversal anyway
    if (!/^[a-z0-9_-]+$/i.test(id)) throw httpError(400, "Invalid project id");
    return path.join(this.dir, id + ".json");
  }

  async list() {
    const files = await fs.readdir(this.dir);
    const out = [];
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      try {
        const p = JSON.parse(await fs.readFile(path.join(this.dir, f), "utf8"));
        out.push(summary(p));
      } catch { /* skip unreadable */ }
    }
    out.sort((a, b) => (b.updatedAt || 0) - (a.updatedAt || 0));
    return out;
  }

  async get(id) {
    let raw;
    try { raw = await fs.readFile(this._file(id), "utf8"); }
    catch { throw httpError(404, "Project not found"); }
    return JSON.parse(raw);
  }

  async create(name, model) {
    const id = crypto.randomBytes(8).toString("hex");
    const now = Date.now();
    const project = {
      id, name: (name || "Untitled").trim() || "Untitled",
      rev: 1, createdAt: now, updatedAt: now,
      model: model || emptyModel(),
    };
    await this._write(project);
    return project;
  }

  // save expects the rev the client started from; bumps rev on success
  async save(id, { name, model, rev }) {
    const cur = await this.get(id);
    if (typeof rev === "number" && rev !== cur.rev) {
      throw httpError(409, `Conflict: project was modified (server rev ${cur.rev}, you have ${rev}). Reload before saving.`);
    }
    cur.name = (name != null ? name : cur.name);
    if (model != null) cur.model = model;
    cur.rev = cur.rev + 1;
    cur.updatedAt = Date.now();
    await this._write(cur);
    return cur;
  }

  async rename(id, name) {
    const cur = await this.get(id);
    cur.name = (name || cur.name).trim() || cur.name;
    cur.updatedAt = Date.now();
    await this._write(cur);
    return cur;
  }

  async remove(id) {
    try { await fs.unlink(this._file(id)); }
    catch { throw httpError(404, "Project not found"); }
  }

  async _write(project) {
    // write-then-rename for atomicity
    const tmp = this._file(project.id) + ".tmp";
    await fs.writeFile(tmp, JSON.stringify(project, null, 2));
    await fs.rename(tmp, this._file(project.id));
  }
}

function summary(p) {
  const m = p.model || {};
  return {
    id: p.id, name: p.name, rev: p.rev,
    createdAt: p.createdAt, updatedAt: p.updatedAt,
    elements: (m.elements || []).length,
    diagrams: (m.diagrams || []).length,
  };
}

function emptyModel() {
  return { name: "Model", elements: [], relationships: [], diagrams: [] };
}

function httpError(status, message) {
  const e = new Error(message);
  e.status = status;
  return e;
}

module.exports = { Store, emptyModel, httpError };
